import {
  Poppins
} from 'next/font/google';
import './globals.css';

import { ClerkProvider, auth } from '@clerk/nextjs';
import UserMenu from '@/components/UserMenu';
import { isTeacher } from '@/lib/isTeacher';


const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500"],

});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const { userId } = auth();

  if (isTeacher(userId)) {
    //   return redirect("/guardian");
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <main className="text-black bg-gradient-custom font-bold flex justify-between flex-col  p-4 h-screen">
            <UserMenu />
            {children}

          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
