import { Poppins } from "next/font/google";
import "./globals.css";
import { redirect } from "next/navigation";

import { ClerkProvider, auth } from "@clerk/nextjs";
import UserMenu from "@/components/UserMenu";
import { isTeacher } from "@/lib/isTeacher";
import { useRouter } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <main className="text-black bg-gradient-custom font-bold flex justify-between flex-col  p-4 h-screen">
            <UserMenu />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
